### ISSUE TITLE
Problemas ao acesso ao codigo

### ISSUE THREAD

**Issue by exodojaffar** [joao-lucas-paes/trabalhoDaEscola#2]
Ao deixar o código no client, fica a possibilidade do usuário manipular o código, assim estragando o jogo, se o jogador tiver tal possibilidade.

**Comment by joao-lucas-paes** [comment]
o objetivo é que ele só atrapalhe, o client pode acessar a vontade, já que não faz sentido ele no meio de uma corrida perder tempo pra mexer no código do site
